permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 蒋关富 
  email: brucejiang.jgf@gmail.com; xile.jgf@taobao.com
  link: http://xubin-dragon.com
  weibo: 
  github: http://github.com/brucejiang-jgf

# 站点信息
title: xubin-dragon的博客 
description: 纪念我的小屁孩：旭彬胖子：）
url: http://xubin-dragon.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://xubin-dragon.com/public/img/head.jpg 
favicon: http://xubin-dragon.com/public/img/head.ico 

# google analytics 设置
ga:
  id: UA-54767140-1
  url: xubin-dragon.com

# disqus 设置
disqus:
shortname: xubin-dragon-zh

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
