permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: brucejiang.jgf 
name: 蒋关富 
email: brucejiang.jgf@gmail.com; xile.jgf@taobao.com
link: http://xubin-dragon.com
weibo: 
github: http://github.com/brucejiang-jgf

# 站点信息
title: xubin-dragon's bolg 
description: 纪念我的小屁孩：旭彬胖子：）
url: http://xubin-dragon.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://xubin-dragon.com/public/img/head.jpg 
favicon: http://xubin-dragon.com/public/img/head.ico 

# google analytics 设置
ga:
  id: UA-54767140-1
  url: xubin-dragon.com

# disqus 设置
disqus:
shortname: xubin-dragon-zh

# 主题设置，自动激活某个标签
active: abing-pvm 

# 首页除了最新文章外显示分类
cates: 
  - abing-pvm 
  - jvm 

# 中文本地化
locals:
  tags: Tags 
  about: About 
  newest: Newest 
  archive: Archive 
  content: Content 
